spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:config-server
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config-server
server:
  port: 9100

eureka:
  client:
    service-url:
      default-zone: discoveryservice:8761/eureka