spring:
  application:
    name: discovery-service
  config:
    import: optional:configserver:config-server
    cloud:
      config:
        discovery:
          enabled: true
          service-id: config-server
      loadbalancer:
        ribbon:
          enabled: false

server:
  port: 8761

eureka:
  instance:
    hostname: discoveryservice
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"